In [1]:
# Devloping the model using a MNIST database
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout
import numpy as np

In [2]:
mnist = keras.datasets.mnist

In [3]:
# mnist dataset object
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

In [4]:
# download mnist dtaset
mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [5]:
keras.datasets.mnist.load_data()

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [6]:
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

In [7]:
x_train.shape

(60000, 28, 28)

In [8]:
x_test.shape

(10000, 28, 28)

In [9]:
# Print the shape of the array
print("Train Image Shape: ",x_train.shape)
print("Train labels Shape: ",y_train.shape)
print("Test Image Shape: ",x_test.shape)
print("Test labels Shape: ",y_test.shape)

Train Image Shape:  (60000, 28, 28)
Train labels Shape:  (60000,)
Test Image Shape:  (10000, 28, 28)
Test labels Shape:  (10000,)


Scalling the image

In [10]:
# we are scalling the image between 0 to 1
x_train = x_train.astype("float32")/255
x_test = x_test.astype("float32")/255

In [11]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [12]:
x_train = np.expand_dims(x_train,-1)  # we added extra dimention '1'

In [13]:
x_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [14]:
x_train.shape

(60000, 28, 28, 1)

In [15]:
x_test = np.expand_dims(x_test,-1)


In [16]:
x_test.shape

(10000, 28, 28, 1)

In [18]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [19]:
# how to make embedings
# convert class vector to binary class matrices
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [20]:
print(y_train)   # for diffrent classes previously available in y_train like 5, 0, 4 ..... the are conveted into vector 0.0.0

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [21]:
print(y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
y_train.shape

(60000, 10)

In [23]:
mnist_model = Sequential()

In [24]:
# adding first layer i.e convulation layer
mnist_model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(28,28,1)))           # 32 is the filter size # 3*3 matrix filter # image is 28*28 and 1 represent it the gray scale image
# pooling layer
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
#another convulation layer  # with added more filters
mnist_model.add(Conv2D(64,kernel_size=(3,3),activation='relu'))
# again pooling layer
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
# added extra layer i.e flattern layer
mnist_model.add(Flatten())
# we added dropout layer bacause we have to controll neurons  # to avoid overfit the model
mnist_model.add(Dropout(0.5))
# final layer we need to add Dence layer
mnist_model.add(Dense(10,activation="softmax"))  # it is binary classification model thats why activation function is "softmax" #we have 10 diffrent classes (columns) that whay 10



In [26]:
mnist_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)              0

In [34]:
# compile the model
mnist_model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [35]:
mnist_model

In [29]:
x_train.shape

(60000, 28, 28, 1)

In [30]:
x_test.shape

(10000, 28, 28, 1)

In [31]:
y_train.shape

(60000, 10)

In [32]:
y_test.shape

(10000, 10)

In [36]:
# noe fiiting the model
# we are processing 128 embedding at a time #
mnist_model.fit(x_train,y_train, batch_size=128,epochs=15,validation_split=0.1)

Epoch 1/15
422/422 [==============================] - 43s 100ms/step - loss: 0.3734 - accuracy: 0.8876 - val_loss: 0.0839 - val_accuracy: 0.9777
Epoch 2/15
422/422 [==============================] - 41s 97ms/step - loss: 0.1144 - accuracy: 0.9647 - val_loss: 0.0561 - val_accuracy: 0.9837
Epoch 3/15
422/422 [==============================] - 40s 95ms/step - loss: 0.0848 - accuracy: 0.9734 - val_loss: 0.0458 - val_accuracy: 0.9875
Epoch 4/15
422/422 [==============================] - 40s 96ms/step - loss: 0.0716 - accuracy: 0.9784 - val_loss: 0.0416 - val_accuracy: 0.9888
Epoch 5/15
422/422 [==============================] - 41s 96ms/step - loss: 0.0628 - accuracy: 0.9803 - val_loss: 0.0398 - val_accuracy: 0.9898
Epoch 6/15
422/422 [==============================] - 41s 98ms/step - loss: 0.0565 - accuracy: 0.9821 - val_loss: 0.0371 - val_accuracy: 0.9888
Epoch 7/15
422/422 [==============================] - 40s 96ms/step - loss: 0.0538 - accuracy: 0.9827 - val_loss: 0.0349 - val_accuracy

In [37]:
score = mnist_model.evaluate(x_test,y_test,verbose=0)
print("Test loss: ",score[0])
print("Test accuracy: ",score[1])

Test loss:  0.026800042018294334
Test accuracy:  0.9912999868392944
